import { Chat } from "../types/Chat";
import { Daniel, Dylan, Matheus, Thiago } from "./users";

export const fakeChats: Chat[] = [
  {
    id: "1",
    name: Matheus.id,
    lastSeen: 1650487006093,
    messages: [
      {
        id: "1",
        text: "Welcome",
        sender: Thiago,
        timestamp: 1650487006982,
        reactions: [],
      },
      {
        id: "2",
        text: "Would you rather be an apple or an orange?",
        sender: Matheus,
        timestamp: 1650487006983,
        reactions: [],
      },
      {
        id: "3",
        text: "Why are you here today?",
        sender: Thiago,
        timestamp: 1650487006984,
        reactions: [],
      },
      {
        id: "4",
        text: " look inside and find",
        sender: Matheus,
        timestamp: 1650487006985,
        reactions: [],
      },
      {
        id: "5",
        text: "Would you like to see into the future? Why?",
        sender: Thiago,
        timestamp: 1650487006986,
        reactions: [],
      },
      {
        id: "6",
        text: "I like work; it fascinates me. I can sit and look at it for hours.",
        sender: Matheus,
        timestamp: 1650487006987,
        reactions: [],
      },
      {
        id: "7",
        text: "I see you find yourself very interesting",
        sender: Thiago,
        timestamp: 1650487006988,
        reactions: [],
      },
      {
        id: "8",
        text: "meaning?",
        sender: Matheus,
        timestamp: 1650487006989,
        reactions: [],
      },
      {
        id: "9",
        parentId: "8",
        text: "really?",
        sender: Thiago,
        timestamp: 1650487006990,
        reactions: [],
      },
      {
        id: "10",
        text: "help me",
        sender: Matheus,
        timestamp: 1650487006991,
        reactions: [{ emoji: "🙅‍♀️", user: Thiago }],
      },
      {
        id: "11",
        text: "how may I guide you",
        sender: Thiago,
        timestamp: 1650487006991,
        reactions: [
          { emoji: "✌", user: Matheus },
          { emoji: "🍉", user: Matheus },
        ],
      },
      {
        id: "12",
        parentId: "11",
        text: "because one is beer with clamato and the other is like a smoothie",
        sender: Matheus,
        timestamp: 1650487006993,
        reactions: [],
      },
    ],
  },
  {
    id: "2",
    name: Daniel.id,
    lastSeen: 1650331578014,
    messages: [
      {
        id: "1",
        text: "Hello there. Thanks for the follow. Did you notice, that I am an egg? A talking egg? Damn!",
        sender: Daniel,
        timestamp: 1650331578011,
        reactions: [],
      },
      {
        id: "2",
        text: "Yeah that is crazy, but people can change their own picture and build their own Twitter conversation with this generator, so it does not matter that you are an egg",
        sender: Thiago,
        timestamp: 1650331578012,
        reactions: [],
      },
      {
        id: "3",
        text: "Thanks mate! Feel way better now. Oh, and guys, these messages will be removed once your add your own :-)",
        sender: Daniel,
        timestamp: 1650331578013,
        reactions: [],
      },
    ],
  },
  {
    id: "3",
    name: Dylan.id,
    lastSeen: 1650331578099,
    messages: [
      {
        id: "1",
        text: "Hello there. Thanks for the follow. Did you notice, that I am an egg? A talking egg? Damn!",
        sender: Dylan,
        timestamp: 1650331578100,
        reactions: [],
      },
      {
        id: "2",
        text: "Hello there. Thanks for the follow. Did you notice, that I am an egg? A talking egg? Damn!",
        sender: Dylan,
        timestamp: 1650331578101,
        reactions: [],
      },
      {
        id: "3",
        text: "Yeah that is crazy, but people can change their own picture and build their own Twitter conversation with this generator, so it does not matter that you are an egg",
        sender: Thiago,
        timestamp: 1650331578102,
        reactions: [],
      },
      {
        id: "4",
        text: "Thanks mate! Feel way better now. Oh, and guys, these messages will be removed once your add your own :-)",
        sender: Dylan,
        timestamp: 1650331578103,
        reactions: [],
      },
      {
        id: "5",
        text: "Thanks mate! Feel way better now. Oh, and guys, these messages will be removed once your add your own :-)",
        sender: Dylan,
        timestamp: 1650331578104,
        reactions: [],
      },
      {
        id: "6",
        text: "Thanks mate! Feel way better now. Oh, and guys, these messages will be removed once your add your own :-)",
        sender: Dylan,
        timestamp: 1650331578104,
        reactions: [],
      },
      {
        id: "7",
        text: "hey",
        sender: Thiago,
        timestamp: 1650331578105,
        reactions: [],
      },
      {
        id: "8",
        text: "hey",
        sender: Thiago,
        timestamp: 1650331578106,
        reactions: [],
      },
      {
        id: "9",
        text: "hey",
        sender: Thiago,
        timestamp: 1650331578107,
        reactions: [],
      },
      {
        id: "10",
        parentId: "3",
        text: "hey",
        sender: Thiago,
        timestamp: 1650331578108,
        reactions: [],
      },
      {
        id: "11",
        text: "hey",
        sender: Thiago,
        timestamp: 1652054022839,
        reactions: [],
      },
      {
        id: "12",
        text: "heyoo",
        sender: Thiago,
        timestamp: 1652107921225,
        reactions: [],
      },
    ],
  },
];
